name: fl-py37
channels:
  - pytorch
  - defaults
dependencies:
  - astroid=2.2.5
  - autopep8=1.4.4
  - blas=1.0
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - cffi=1.12.3
  - cycler=0.10.0
  - freetype=2.9.1
  - intel-openmp=2019.4
  - isort=4.3.20
  - joblib=0.13.2
  - jpeg=9b
  - kiwisolver=1.1.0
  - lazy-object-proxy=1.4.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libpng=1.6.37
  - libtiff=4.0.10
  - matplotlib=3.1.0
  - mccabe=0.6.1
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1c
  - pandas=0.24.2
  - pillow=6.0.0
  - pip=19.1.1
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pylint=2.3.1
  - pyparsing=2.4.0
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytorch=1.1.0
  - pytz=2019.1
  - readline=7.0
  - rope=0.14.0
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - tk=8.6.8
  - torchvision=0.3.0
  - tornado=6.0.2
  - wheel=0.33.4
  - wrapt=1.11.1
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
prefix: /Users/zakharykaplan/.miniconda3/envs/fl-py37

